name = "hello-meta"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "hello-meta_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "hello-meta.wasm"
command = "npm run build:release"
